language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script: npm run-script deploy
env:
    global:
        - GH_REF: github.com/snowpeame/snowpeas
        - secure: sFORrd8RuREojumxVt121evh9V642/vQIxe0MCke6ztzInghmQ9AXgLFw92WfunKAQHoSdflyUCIcIoC7wBrY1tTNY+m+3AtvtY5cBXNJ0r9ynLOXLPBtYP803cMtq8h6UVHdnr1KL0ziuINGC7uRRrf6a7KzvB71Zic7WNrYds=

branches:
    only:
        - master
